name: mechanical-markdown

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VER: 3.7.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VER }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VER }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -rdev-requirements.txt
    - name: Run Linter
      run: |
        tox -e flake8
    - name: Run unit-tests
      run: |
        tox -e py310
    - name: Run examples
      run: |
        tox -e examples
    - name: Upload test coverage
      uses: codecov/codecov-action@v1
    - name: Build and publish mechanical-markdown
      if: startswith(github.ref, 'refs/tags/v')
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
